stages:
  data_ingestion_cleaning:
    desc: apply basic cleaning and remove unwanted/columns with missing values and
      stores the cleaned data
    cmd: python .\src\data_cleaning.py --force
    deps:
    - .\data\raw\sampled_data.csv
    - .\src\data_cleaning.py
    outs:
    - .\data\processed\
