# XGBoost model parameters
xgb_params:
  max_depth: 5
  learning_rate: 0.1
  n_estimators: 200
  min_child_weight: 3
  gamma: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

# Feature transformation parameters
feature_params:
  quantile_cols:
    - Temperature(F)
    - Humidity(%)
    - Pressure(in)
    - Visibility(mi)
    - Wind_Speed(mph)
    - Total_Time
    - Start_Lng
    - Start_Lat
  
  categorical_cols:
    - City
    - County
    - State

# Data split parameters
split_params:
  test_size: 0.1
  val_size: 0.167
  random_state: 42

# File paths
paths:
  input_path: data/processed/featured_data.csv
  model_dir: ./models
  log_dir: ./logs
  model_name: xgb_model